#podman run --name mongodb -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=user -e MONGO_INITDB_ROOT_PASSWORD=pass -d 
services:
  mongo-db:
    image: mongodb/mongodb-community-server:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - ../data:/data/db
  web-server:
    image: collector/web-server:latest
    ports:
      - "8000:8081"
    depends_on:
      - mongo-db
    environment:
      - SPRING_DATA_MONGODB_URLI=mongodb://user:pass@mongo-db:27017/users
